application: agenciabdesign

runtime: nodejs10
instance_class: F2
#env_variables:
  #BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /*
  static_dir: public

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto